# Generated by Django 4.1.7 on 2023-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
