# Generated by Django 4.1.7 on 2023-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_orderplaced_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("comment", models.CharField(max_length=500)),
            ],
        ),
    ]
